config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  scope '(:locale)', locale: /en|vi|ja/ do
    root 'discover#top'
    resources :users  do
      member do
        get :activate
      end
    end
    get 'profile/:id' => 'users#profile', as: :profile
    resources :languages
    resources :categories
    resources :nations
    resources :divisions
    resources :payment_vendors
    resources :app_settings, :except => [:new, :create, :destroy]
    resources :faqs
    resources :projects do
      member do
        get 'preview' => 'projects#preview'
        get 'edit_rewards' => 'projects#edit_rewards'
        get 'discard' => 'projects#discard'
        get 'apply' => 'projects#apply'
        get 'remand' => 'projects#remand'
        get 'approve' => 'projects#approve'
        get 'resume' => 'projects#resume'
        get 'suspend' => 'projects#suspend'
        get 'drop' => 'projects#drop'
        get 'pay'
        get 'pay_back'
      end
      collection do
        get 'pledge_list'
        get 'start' => 'projects#start'
        get 'complete'
        get 'cancel'
      end
    end
    get 'project/:project_code' => 'projects#show_by_code', as: :project_by_code
    get 'rewards/:reward_code/new_pledge' => 'pledges#new', as: :new_pledge
    post 'shipping_rate' => 'pledges#shipping_rate'
    resources :pledges, :except => :new do
      member do
        get 'pay'
        get 'pay_back'
        get 'complete'
        get 'cancel'
      end
    end

    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout
    post 'user_sessions' => 'user_sessions#create', :as => :user_sessions

    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
    get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

    get 'discover/top'
    get 'discover/search'
    get 'discover/category/:id' => 'discover#category', as: :discover_category

    get 'pages/faq'
    get 'pages/news'
    get 'pages/news_body/:id' => 'pages#news_body'

    resources :password_resets
    resources :news
    resources :inquiries
    post 'inquiries/create_from_modal'
    get 'dashboard' => 'dashboard#index'
    get 'dashboard/analytics/:id' => 'dashboard#analytics', as: :dashboard_analytics
    get 'dashboard/notifications/:id' => 'dashboard#notifications', as: :dashboard_notifications
    get 'mypage/profile'
    get 'mypage/notifications'
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                              :integer          not null, primary key
#  email                           :string           not null
#  crypted_password                :string
#  salt                            :string
#  created_at                      :datetime
#  updated_at                      :datetime
#  name                            :string
#  is_admin                        :boolean          default(FALSE)
#  activation_state                :string
#  activation_token                :string
#  activation_token_expires_at     :datetime
#  reset_password_token            :string
#  reset_password_token_expires_at :datetime
#  reset_password_email_sent_at    :datetime
#
# Indexes
#
#  index_users_on_activation_token      (activation_token)
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token)
#

class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :authentications, :dependent => :destroy
  has_many :projects, :dependent => :destroy

  accepts_nested_attributes_for :authentications

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validate :unique_email, if: -> { new_record? }
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  def uses_twitter?
    authentications.exists?(provider: :twitter)
  end

  def uses_facebook?
    authentications.exists?(provider: :facebook)
  end

  private

  def unique_email
    errors.add(:email, 'already exists') if User.exists?(email: read_attribute(:email))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin, only: [:index, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :profile]
  before_action :require_self, only: [:edit, :update, :destroy]

  # GET /users/1/activate
  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to login_path, notice: t('msg.user_activated')
    else
      not_authenticated
    end
  end

  # GET /profile/1
  def profile
    if logged_in? && @user == current_user
      redirect_to controller: :mypage, action: :profile
    else
      render :show
    end
  end

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if User.exists?(email: @user.email)
      u = User.find_by(email: @user.email)
      if u.external? || u.activation_state == 'active'
        return redirect_to login_path, notice: t('msg.account_exists')
      else
        User.where(email: @user.email).update_all(email: "#{Time.now.strftime('%Y%m%d-%H%M%S%3N')}-#{@user.email}")
      end
    end

    if @user.save
      if current_user && current_user.is_admin
        redirect_to :users, notice: t('msg.user_created')
      else
        redirect_to root_path, notice: t('msg.please_activate', email: @user.email)
      end
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: t('msg.user_updated')
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: t('msg.user_destroyed')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name,
                                 :authentications_attributes)
  end

  # Filter: him/herself
  def require_self
    render_404 unless @user == current_user
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <%= render partial: 'layouts/error_container', locals: {errors: @user.errors} %>
  <% end %>

  <div class="form-horizontal col-md-offset-2">
    <div class="form-group">
      <%= f.label :name, t('user_model.name'), class: 'control-label col-md-2' %>
      <div class="col-md-4">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, t('user_model.email'), class: 'control-label col-md-2' %>
      <div class="col-md-4">
        <%= f.text_field :email, value: @user.email, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password, t('user_model.password'), class: 'control-label col-md-2' %>
      <div class="col-md-4">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, t('user_model.password_confirmation'), class: 'control-label col-md-2' %>
      <div class="col-md-4">
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-offset-2">
      <% if logged_in? %>
        <%= f.submit t('settings.save_settings'), class: 'btn btn-info' %>
        <span><%= link_to t('settings.view_profile'), @user, class: 'ml2' %></span>
      <% else %>
        <%= f.submit t('signup.signup'), class: 'btn btn-info' %>
        <span>&nbsp;or&nbsp;&nbsp;<%= link_to t('signup.login'), login_path %></span>
      <% end %>
    </div>
  </div>

<% end %>

app/views/users/_show_projects.html.erb
<section>
  <div class="profile-header py4 px2">
    <div class="container">
      <h2 class="mb1">
        <%= @user.name %>
        <% if @user == current_user %>
          <small>
            (<%= link_to t('profile.edit_profile'), edit_user_path(@user) %>)
          </small>
        <% end %>
      </h2>
      <% backed_count = Project.backed_by(@user.id).count %>
      <h4><%= t('profile.backed_count', backed_count: backed_count, pluralized: 'project'.pluralize(backed_count)) %></h4>
      <div class="mt2">
        <% if auth_fb = @user.authentications.find_by(provider: :facebook) %>
          <%= link_to image_tag('icon_fb_48.png'), "http://facebook.com/#{auth_fb.uid.to_s}", target: '_blank' %>
        <% end %>
        <% if auth_tw = @user.authentications.find_by(provider: :twitter) %>
          <%= link_to image_tag('icon_tw_48.png'), "https://twitter.com/intent/user?user_id=#{auth_tw.uid.to_s}", target: '_blank' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="bg-white">
  <div class="container">

    <div class="posted-projects py3">
      <h3 class="my2"><%= t('profile.posted_projects') %></h3>
      <% Project.posted_by(@user).each do |p| %>
        <div class="row project-card-wrap">
          <div class="col-md-10">
            <div class="project-card">
              <div class="project-image">
                <% if p.status_div_draft? || p.status_div_remanded? %>
                  <%= image_tag(p.image(locale)) %>
                <% else %>
                  <%= link_to image_tag(p.image(locale)), project_by_code_path(p.code) %>
                <% end %>
              </div>
              <div class="project-card-description">
                <% sum = p.summary %>
                <h4><%= link_to p.title(locale), project_by_code_path(p.code) %></h4>
                <p><%= link_to p.user.name, p.user %></p>
                <p class="grey-dark"><%= p.blurb(locale) %></p>
                <div class="project-card-footer">
                  <div class="project-location-category">
                    <%= link_to discover_category_path(p.category), class: 'mr2' do %>
                      <i class="glyphicon glyphicon-tag"></i>
                      <%= p.category.name(locale) %>
                    <% end %>
                    <i class="glyphicon glyphicon-globe"></i>
                    <% p.project_locales.each do |l|%>
                      <kbd><%= l.language.code %></kbd>
                    <% end %>
                  </div>
                  <div class="project-status-wrap absolute-bottom">
                    <div class="project-progress mb1">
                      <div class="progress">
                        <div class="progress-bar progress-bar-info" style="width:<%= sum.achieved %>%">
                        </div>
                      </div>
                    </div>
                    <ul class="project-status list-inline">
                      <li class="mr2">
                        <strong class="block h4"><%= sum.achieved %>%</strong>
                        <span class="grey-dark">funded</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4">$<%= sum.funded_amount_f %></strong>
                        <span class="grey-dark">pledged</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4"><%= sum.funded_count %></strong>
                        <span class="grey-dark">backers</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4"><%= p.days_to_go %></strong>
                        <span class="grey-dark">days to go</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-2">
            <p>
              <h5><%= t('profile.status') %></h5>
              <h3 class="mt1 ml2">
                <% if p.finished? %>
                  <%= t('profile.finished') %>
                <% else %>
                  <%= p.status_div.t %>
                <% end %>
              </h3>
            </p>
            <% if p.status_div_draft? || p.status_div_remanded? %>
              <%= link_to t('profile.edit'), edit_project_path(p), class: 'btn btn-default btn-block' %>
            <% elsif p.status_div_active? || p.status_div_suspended? %>
              <%= link_to t('profile.see_pledges'), '#pledge-list-modal',
                class: 'btn btn-default btn-block',
                data: {toggle: 'modal', project_code: p.code} %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="backed-projects py3">
      <h3 class="my2"><%= t('profile.backed_projects') %></h3>
      <% Project.backed_by(@user).each do |p| %>
        <div class="row project-card-wrap">
          <div class="col-md-10">
            <div class="project-card">
              <div class="project-image">
                <%= link_to image_tag(p.image(locale)), project_by_code_path(p.code) %>
              </div>
              <div class="project-card-description">
                <% sum = p.summary %>
                <h4><%= link_to p.title(locale), project_by_code_path(p.code) %></h4>
                <p><%= link_to p.user.name, p.user %></p>
                <p class="grey-dark">Short description about the project. This should be taken from the database. Then it needs to be developed!</p>
                <div class="project-card-footer">
                  <div class="project-location-category">
                    <%= link_to discover_category_path(p.category), class: 'mr2' do %>
                      <i class="glyphicon glyphicon-tag"></i>
                      <%= p.category.name(locale) %>
                    <% end %>
                    <i class="glyphicon glyphicon-globe"></i>
                    <% p.project_locales.each do |l|%>
                      <kbd><%= l.language.code %></kbd>
                    <% end %>
                  </div>
                  <div class="project-status-wrap absolute-bottom">
                    <div class="project-progress mb1">
                      <div class="progress">
                        <div class="progress-bar progress-bar-info" style="width:<%= sum.achieved %>%">
                        </div>
                      </div>
                    </div>
                    <ul class="project-status list-inline">
                      <li class="mr2">
                        <strong class="block h4"><%= sum.achieved %>%</strong>
                        <span class="grey-dark">funded</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4">$<%= sum.funded_amount_f %></strong>
                        <span class="grey-dark">pledged</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4"><%= sum.funded_count %></strong>
                        <span class="grey-dark">backers</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4"><%= p.days_to_go %></strong>
                        <span class="grey-dark">days to go</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-2">
            <p>
              <h5><%= t('profile.status') %></h5>
              <h3 class="mt1 ml2">
                <% if p.finished? %>
                  <%= t('profile.finished') %>
                <% else %>
                  <%= p.status_div.t %>
                <% end %>
              </h3>
            </p>
            <% if p.status_div_active? || p.status_div_suspended? %>
              <%= link_to t('profile.my_pledges'), '#pledge-list-modal',
                class: 'btn btn-default btn-block',
                data: {toggle: 'modal', project_code: p.code, pledged_by: 'me'} %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<div class="modal fade" id="pledge-list-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2 class="my2"><%= t('profile_pledge_modal.pledge_list') %></h2>
      </div>
      <div class="modal-body" id="pledge-list-info">
        <!-- pledge list -->
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $('#pledge-list-modal').on('show.bs.modal', function(event) {
      var project_code = $(event.relatedTarget).data('project-code');
      var pledged_by = $(event.relatedTarget).data('pledged-by');
      var modal = $(this);
      $.ajax({
        url: "/projects/pledge_list",
        type: "GET",
        data: {locale: "<%= locale %>", project_code: project_code, pledged_by: pledged_by},
        dataType: "html",
        success: function(data, status, xhr) {
          return modal.find('#pledge-list-info').html(data);
        },
        error: function(xhr, status, error) {
          modal.modal('hide');
          return alert('Failed to load pledge list!!\n[Error] ' + error);
        }
      });
    });
  });
</script>

app/views/users/edit.html.erb
<section>
  <div class="full-wide-header py4 px2">
    <div class="container">
      <h2 class="mb1 col-md-offset-2"><%= t('settings.settings_title') %></h2>
    </div>
  </div>
</section>

<div class="container bg-white">
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Twitter User</th>
      <th>Facebook User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.uses_twitter?.to_s %></td>
        <td><%= user.uses_facebook?.to_s %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<section>
  <div class="full-wide-header py4 px2">
    <div class="container">
      <h2 class="mb1 col-md-offset-2"><%= t('signup.signup_title') %></h2>
    </div>
  </div>
</section>

<div class="container bg-white">
  <div class="row my1">
    <div class="col-md-6 col-md-offset-2">
      <%= link_to auth_at_provider_path(provider: :facebook), class: 'btn btn-primary btn-block btn-lg my1' do %>
        <h3><%= image_tag('icon_fb_64_w.png', size: '35x35') %>&nbsp;&nbsp;Facebook</h3>
      <% end %>
    </div>
  </div>
  <div class="row my1">
    <div class="col-md-6 col-md-offset-2">
      <%= link_to auth_at_provider_path(provider: :twitter), class: 'btn btn-info btn-block btn-lg my1' do %>
        <h3><%= image_tag('icon_tw_64_w.png', size: '35x35') %>&nbsp;&nbsp;Twitter</h3>
      <% end %>
    </div>
  </div>
  <div class="row my2">
    <div class="col-md-2 col-md-offset-2">
      <hr>
    </div>
    <div class="col-md-2 center pt1">
      <span><%= t('signup.or') %></span>
    </div>
    <div class="col-md-2">
      <hr>
    </div>
    <div class="col-md-4">
    </div>
  </div>

  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<section>
  <div class="profile-header py4 px2">
    <div class="container">
      <h2 class="mb1">
        <%= @user.name %>
        <% if @user == current_user %>
          <small>
            (<%= link_to t('profile.edit_profile'), edit_user_path(@user) %>)
          </small>
        <% end %>
      </h2>
      <% backed_count = Project.backed_by(@user.id).count %>
      <h4><%= t('profile.backed_count', backed_count: backed_count, pluralized: 'project'.pluralize(backed_count)) %></h4>
      <div class="mt2">
        <% if auth_fb = @user.authentications.find_by(provider: :facebook) %>
          <%= link_to image_tag('icon_fb_48.png'), "http://facebook.com/#{auth_fb.uid.to_s}", target: '_blank' %>
        <% end %>
        <% if auth_tw = @user.authentications.find_by(provider: :twitter) %>
          <%= link_to image_tag('icon_tw_48.png'), "https://twitter.com/intent/user?user_id=#{auth_tw.uid.to_s}", target: '_blank' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="bg-white">
  <div class="container">

    <div class="posted-projects py3">
      <h3 class="my2"><%= t('profile.posted_projects') %></h3>
      <% Project.posted_by(@user).each do |p| %>
        <div class="row project-card-wrap">
          <div class="col-md-10">
            <div class="project-card">
              <div class="project-image">
                <% if p.status_div_draft? || p.status_div_remanded? %>
                  <%= image_tag(p.image(locale)) %>
                <% else %>
                  <%= link_to image_tag(p.image(locale)), project_by_code_path(p.code) %>
                <% end %>
              </div>
              <div class="project-card-description">
                <% sum = p.summary %>
                <h4><%= link_to p.title(locale), project_by_code_path(p.code) %></h4>
                <p><%= link_to p.user.name, p.user %></p>
                <p class="grey-dark"><%= p.blurb(locale) %></p>
                <div class="project-card-footer">
                  <div class="project-location-category">
                    <%= link_to discover_category_path(p.category), class: 'mr2' do %>
                      <i class="glyphicon glyphicon-tag"></i>
                      <%= p.category.name(locale) %>
                    <% end %>
                    <i class="glyphicon glyphicon-globe"></i>
                    <% p.project_locales.each do |l|%>
                      <kbd><%= l.language.code %></kbd>
                    <% end %>
                  </div>
                  <div class="project-status-wrap absolute-bottom">
                    <div class="project-progress mb1">
                      <div class="progress">
                        <div class="progress-bar progress-bar-info" style="width:<%= sum.achieved %>%">
                        </div>
                      </div>
                    </div>
                    <ul class="project-status list-inline">
                      <li class="mr2">
                        <strong class="block h4"><%= sum.achieved %>%</strong>
                        <span class="grey-dark">funded</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4">$<%= sum.funded_amount_f %></strong>
                        <span class="grey-dark">pledged</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4"><%= sum.funded_count %></strong>
                        <span class="grey-dark">backers</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4"><%= p.days_to_go %></strong>
                        <span class="grey-dark">days to go</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-2">
            <p>
              <h5><%= t('profile.status') %></h5>
              <h3 class="mt1 ml2">
                <% if p.finished? %>
                  <%= t('profile.finished') %>
                <% else %>
                  <%= p.status_div.t %>
                <% end %>
              </h3>
            </p>
            <% if p.status_div_draft? || p.status_div_remanded? %>
              <%= link_to t('profile.edit'), edit_project_path(p), class: 'btn btn-default btn-block' %>
            <% elsif p.status_div_active? || p.status_div_suspended? %>
              <%= link_to t('profile.see_pledges'), '#pledge-list-modal',
                class: 'btn btn-default btn-block',
                data: {toggle: 'modal', project_code: p.code} %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="backed-projects py3">
      <h3 class="my2"><%= t('profile.backed_projects') %></h3>
      <% Project.backed_by(@user).each do |p| %>
        <div class="row project-card-wrap">
          <div class="col-md-10">
            <div class="project-card">
              <div class="project-image">
                <%= link_to image_tag(p.image(locale)), project_by_code_path(p.code) %>
              </div>
              <div class="project-card-description">
                <% sum = p.summary %>
                <h4><%= link_to p.title(locale), project_by_code_path(p.code) %></h4>
                <p><%= link_to p.user.name, p.user %></p>
                <p class="grey-dark">Short description about the project. This should be taken from the database. Then it needs to be developed!</p>
                <div class="project-card-footer">
                  <div class="project-location-category">
                    <%= link_to discover_category_path(p.category), class: 'mr2' do %>
                      <i class="glyphicon glyphicon-tag"></i>
                      <%= p.category.name(locale) %>
                    <% end %>
                    <i class="glyphicon glyphicon-globe"></i>
                    <% p.project_locales.each do |l|%>
                      <kbd><%= l.language.code %></kbd>
                    <% end %>
                  </div>
                  <div class="project-status-wrap absolute-bottom">
                    <div class="project-progress mb1">
                      <div class="progress">
                        <div class="progress-bar progress-bar-info" style="width:<%= sum.achieved %>%">
                        </div>
                      </div>
                    </div>
                    <ul class="project-status list-inline">
                      <li class="mr2">
                        <strong class="block h4"><%= sum.achieved %>%</strong>
                        <span class="grey-dark">funded</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4">$<%= sum.funded_amount_f %></strong>
                        <span class="grey-dark">pledged</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4"><%= sum.funded_count %></strong>
                        <span class="grey-dark">backers</span>
                      </li>
                      <li class="mr2">
                        <strong class="block h4"><%= p.days_to_go %></strong>
                        <span class="grey-dark">days to go</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-2">
            <p>
              <h5><%= t('profile.status') %></h5>
              <h3 class="mt1 ml2">
                <% if p.finished? %>
                  <%= t('profile.finished') %>
                <% else %>
                  <%= p.status_div.t %>
                <% end %>
              </h3>
            </p>
            <% if p.status_div_active? || p.status_div_suspended? %>
              <%= link_to t('profile.my_pledges'), '#pledge-list-modal',
                class: 'btn btn-default btn-block',
                data: {toggle: 'modal', project_code: p.code, pledged_by: 'me'} %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<div class="modal fade" id="pledge-list-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2 class="my2"><%= t('profile_pledge_modal.pledge_list') %></h2>
      </div>
      <div class="modal-body" id="pledge-list-info">
        <!-- pledge list -->
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $('#pledge-list-modal').on('show.bs.modal', function(event) {
      var project_code = $(event.relatedTarget).data('project-code');
      var pledged_by = $(event.relatedTarget).data('pledged-by');
      var modal = $(this);
      $.ajax({
        url: "/projects/pledge_list",
        type: "GET",
        data: {locale: "<%= locale %>", project_code: project_code, pledged_by: pledged_by},
        dataType: "html",
        success: function(data, status, xhr) {
          return modal.find('#pledge-list-info').html(data);
        },
        error: function(xhr, status, error) {
          modal.modal('hide');
          return alert('Failed to load pledge list!!\n[Error] ' + error);
        }
      });
    });
  });
</script>