config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  scope '(:locale)', locale: /en|vi|ja/ do
    root 'discover#top'
    resources :users  do
      member do
        get :activate
      end
    end
    get 'profile/:id' => 'users#profile', as: :profile
    resources :languages
    resources :categories
    resources :nations
    resources :divisions
    resources :payment_vendors
    resources :app_settings, :except => [:new, :create, :destroy]
    resources :faqs
    resources :projects do
      member do
        get 'preview' => 'projects#preview'
        get 'edit_rewards' => 'projects#edit_rewards'
        get 'discard' => 'projects#discard'
        get 'apply' => 'projects#apply'
        get 'remand' => 'projects#remand'
        get 'approve' => 'projects#approve'
        get 'resume' => 'projects#resume'
        get 'suspend' => 'projects#suspend'
        get 'drop' => 'projects#drop'
        get 'pay'
        get 'pay_back'
      end
      collection do
        get 'pledge_list'
        get 'start' => 'projects#start'
        get 'complete'
        get 'cancel'
      end
    end
    get 'project/:project_code' => 'projects#show_by_code', as: :project_by_code
    get 'rewards/:reward_code/new_pledge' => 'pledges#new', as: :new_pledge
    post 'shipping_rate' => 'pledges#shipping_rate'
    resources :pledges, :except => :new do
      member do
        get 'pay'
        get 'pay_back'
        get 'complete'
        get 'cancel'
      end
    end

    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout
    post 'user_sessions' => 'user_sessions#create', :as => :user_sessions

    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
    get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

    get 'discover/top'
    get 'discover/search'
    get 'discover/category/:id' => 'discover#category', as: :discover_category

    get 'pages/faq'
    get 'pages/news'
    get 'pages/news_body/:id' => 'pages#news_body'

    resources :password_resets
    resources :news
    resources :inquiries
    post 'inquiries/create_from_modal'
    get 'dashboard' => 'dashboard#index'
    get 'dashboard/analytics/:id' => 'dashboard#analytics', as: :dashboard_analytics
    get 'dashboard/notifications/:id' => 'dashboard#notifications', as: :dashboard_notifications
    get 'mypage/profile'
    get 'mypage/notifications'
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_admin, only: [:destroy, :remand, :approve, :resume, :drop, :pay, :pay_back]
  before_action :set_project, only: [:show, :preview, :edit, :edit_rewards, :update, :destroy, :discard, :apply, :approve, :resume, :remand, :suspend, :drop, :pay, :pay_back]
  before_action :require_login, except: [:index, :show, :show_by_code, :start]
  before_action :require_creator, only: [:discard, :apply, :suspend]
  before_action :require_creator_allowed, only: [:edit, :edit_rewards, :update]

  include AdaptivePayments

  # GET /projects
  def index
    @projects = Project.all.order(:id)
  end

  # GET /projects/pledge_list
  # for ajax
  def pledge_list
    p = Project.active.find_by(code: params[:project_code])
    @pledges = p.backed_pledges

    if p.user != current_user || params[:pledged_by] == 'me'
      @pledges = @pledges.where(user: current_user)
    end

    render partial: 'show_pledge_list'
  end

  # GET /projects/1
  def show
  end

  # GET /project/:project_code
  # To set project_code to address bar.
  # Be sure to exist valid active project.
  def show_by_code
    @project = Project.find_by(code: params[:project_code])
    require_creator if !@project.status_div_active?
    render :show
  end

  # GET /projects/1/preview
  def preview
    render :show
  end

  # GET /projects/start
  def start
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    if @project.status_div_active?
      @project = @project.replicate
      @project.status_div = Divs::ProjectStatus::TEMP
      @project.save
    end
  end

  # GET /projects/1/edit_rewards
  def edit_rewards
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @project.status_div = Divs::ProjectStatus::DRAFT
    @project.code = Time.now.strftime('%Y%m%d-%H%M%S%3N') + '-by-' + current_user.id.to_s
    @project.commission_rate = AppSetting.default_commission_rate

    if @project.save(validate: params[:save_draft].blank?)
      if params[:save_draft]
        redirect_to :back, notice: t('msg.draft_saved')
      elsif params[:edit_rewards]
        redirect_to edit_rewards_project_path(@project)
      end
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if params[:project].present?
      @project.assign_attributes(project_params)
    end

    if params[:preview]
      unless @project.rewards_exist
        return render :edit_rewards
      end
    end

    if @project.save(validate: params[:save_draft].blank?)
      if params[:edit_rewards]
        redirect_to edit_rewards_project_path(@project)
      elsif params[:save_draft]
        redirect_to :back, notice: t('msg.draft_saved')
      elsif params[:preview]
        redirect_to preview_project_path(@project)
      end
    else
      if params[:update_rewards]
        render :edit_rewards
      else
        render :edit
      end
    end
  end

  # GET /projects/1/discard
  def discard
    @project.discard!
    redirect_to projects_url, notice: t('msg.project_discarded')
  end

  # GET /projects/1/apply
  def apply
    @project.apply!
    redirect_to @project, notice: t('msg.project_applied')
  end

  # GET /projects/1/remand
  def remand
    @project.remand!
    redirect_to @project, notice: t('msg.project_remanded')
  end

  # GET /projects/1/approve
  def approve
    @project.approve!
    redirect_to @project, notice: t('msg.project_approved')
  end

  # GET /projects/1/resume
  def resume
    @project.resume!
    redirect_to @project, notice: t('msg.project_resumed')
  end

  # GET /projects/1/suspend
  def suspend
    @project.suspend!
    redirect_to @project, notice: t('msg.project_suspended')
  end

  # GET /projects/1/drop
  def drop
    @project.drop!
    redirect_to projects_url, notice: t('msg.project_dropped')
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: t('msg.project_destroyed')
  end

  # GET /project/1/pay
  def pay
    s_cnt = f_cnt = 0
    @project.pledges_to_pay.each do |pledge|
      if pay_to_creator(pledge)
        s_cnt += 1
      else
        f_cnt += 1
      end
    end

    redirect_to projects_path, notice: t('msg.payment_completed_cnt', s_cnt: s_cnt, f_cnt: f_cnt)
  end

  # GET /project/1/pay_back
  def pay_back
    s_cnt = f_cnt = 0
    @project.pledges_to_pay.each do |pledge|
      if pay_back_to_backer(pledge)
        s_cnt += 1
      else
        f_cnt += 1
      end
    end

    redirect_to projects_path, notice: t('msg.back_payment_completed_cnt', s_cnt: s_cnt, f_cnt: f_cnt)
  end

  # GET /projects/complete
  def complete
    redirect_to @project, notice: t('msg.payment_completed')
  end

  # GET /projects/cancel
  def cancel
    redirect_to @project, notice: t('msg.payment_canceled')
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def project_params
    logger.debug(params)
    params[:project][:project_locales_attributes].try(:each) do |index, hash|
      if hash[:use_this_language] == "0"
        hash[:_destroy] = true
        params[:project][:project_headers_attributes][index][:_destroy] = true
        params[:project][:project_contents_attributes][index][:_destroy] = true
      end
      hash[:is_main] = hash[:language_id] == params[:project][:main_language_id]
    end
    params[:project][:rewards_attributes].try(:each) do |index, hash|
      if hash[:ships_to_div].to_i == Divs::RewardShipsTo::NO_SHIPPING
        hash[:default_shipping_rate] = nil
        hash[:reward_shippings_attributes].try(:each) { |i_rs, h_rs| h_rs[:_destroy] = true }
      elsif hash[:ships_to_div].to_i == Divs::RewardShipsTo::CERTAIN_COUNTRIES
        hash[:default_shipping_rate] = nil
      end
    end
    params.require(:project).permit(
      :id,
      # :code,
      :category_id,
      :goal_amount,
      :duration_days,
      :applied_begin_date,
      :paypal_account,
      project_locales_attributes: [
        :id,
        :language_id,
        :is_main,
        :use_this_language,
        :_destroy
      ],
      project_headers_attributes: [
        :id,
        :language_id,
        :image,
        :image_cache,
        :title,
        :blurb,
        :_destroy
      ],
      project_contents_attributes: [
        :id,
        :language_id,
        :body,
        :_destroy
      ],
      rewards_attributes: [
        :id,
        :price,
        :count,
        :estimated_delivery,
        :ships_to_div,
        :default_shipping_rate,
        :_destroy,
        reward_shippings_attributes: [
          :id,
          :nation_id,
          :shipping_rate,
          :_destroy
        ],
        reward_contents_attributes: [
          :id,
          :language_id,
          :title,
          :image,
          :image_cache,
          :description,
          :_destroy
        ]
      ]
    )
  end

  # Filter: creator of the project
  def require_creator
    render_404 unless @project.user == current_user || is_admin?
  end

  # Filter: creator of the project and allowed to edit
  def require_creator_allowed
    return render_404 unless @project.user == current_user || is_admin?

    unless @project.status_div_draft? || @project.status_div_remanded? || @project.status_div_active? || @project.status_div_temp?
      redirect_to projects_url, alert: t('msg.project_not_editable_because', status: @project.status_div.t)
    end
  end
end

app/views/projects/_form_rewards.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <%= render partial: 'layouts/error_container', locals: {errors: @project.errors} %>
  <% end %>

  <section>
    <div class="full-wide-header py3 px2">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div class="row">
              <div class="col-md-6">
                <%= link_to edit_project_path(@project), class: 'btn btn-default btn-lg btn-block' do %>
                  <%= t('project_edit.step_1') %>
                  <br><br>
                  <h3><%= t('project_edit.step_basics') %></h3>
                <% end %>
              </div>
              <div class="col-md-6">
                <%= link_to '#', class: 'btn btn-primary btn-lg btn-block' do %>
                  <%= t('project_edit.step_2') %>
                  <br><br>
                  <h3><%= t('project_edit.step_rewards') %></h3>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container py2">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <% @project.rewards.build if @project.rewards.size == 0 %>
          <%= f.fields_for :rewards do |rf| %>
            <%= render partial: "reward_form", locals: {f: rf} %>
          <% end %>
          <%= link_to_add_field(t('project_edit.add_reward'), f, :rewards, {}) %>

          <%= hidden_field_tag :update_rewards, :true %>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container py2">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="row">
            <div class="col-md-6">
              <%= f.submit t('project_edit.save_draft'), name: :save_draft, class: 'btn btn-default btn-lg btn-block' %>
            </div>
            <div class="col-md-6">
              <%= f.submit t('project_edit.preview'), name: :preview, class: 'btn btn-info btn-lg btn-block' %>
            </div>
          </div>
          <h4 class="pt2">
            <%= link_to t('project_edit.discard'), discard_project_path(@project), data: { confirm: 'Are you sure?' } %>&nbsp;|
            <%= link_to t('project_edit.back_to_step_1'), edit_project_path(@project) %>
          </h4>
        </div>
      </div>
    </div>
  </section>

<% end %>

app/views/projects/_project_content_form.html.erb
<div class="form-group">
  <%= f.label :body, t('project_model.body') %>
  <%= f.cktext_area :body, class: 'ckeditor', ckeditor: {toolbar: :mini, height: 500} %>
</div>
<%= f.hidden_field :language_id %>
<%= f.hidden_field :id %>

app/views/projects/_project_header_form.html.erb
<div class="form-group">
  <%= f.label :title, t('project_model.title') %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :blurb, t('project_model.blurb') %>
  <%= f.text_area :blurb, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :image, t('project_model.image') %>
  <% if f.object.image.present? %>
    <%= image_tag f.object.image.url, height: 300, class: 'mb1' %>
  <% end %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
</div>
<%= f.hidden_field :language_id %>
<%= f.hidden_field :id %>

app/views/projects/_project_locale_form.html.erb
<div class="field">
  <label class="checkbox-inline">
    <% if params['action'] == 'edit' %>
      <% checked = pl.persisted? && !pl.marked_for_destruction? %>
    <% else %>
      <% checked = pl.use_this_language == "1" %>
    <% end %>
    <%= f.check_box :use_this_language, checked: checked %>
    <span><%= t('project_model.use_this_language') %></span>
  </label>
</div>
<%= f.hidden_field :language_id %>
<%= f.hidden_field :id %>

app/views/projects/_reward_content_form.html.erb
<div class="form-group">
  <%= f.label :title, t('reward_model.title') %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :image, t('reward_model.image') %>
  <% if f.object.image.present? %>
    <%= image_tag f.object.image.url, height: 300, class: 'mb1' %>
  <% end %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
</div>
<div class="form-group">
  <%= f.label :description, t('reward_mode.description') %>
  <%= f.text_area :description, class: 'form-control', rows: '6' %>
</div>
<%= f.hidden_field :language_id %>
<%= f.hidden_field :id %>

app/views/projects/_reward_shipping_form.html.erb
<% disabled = disabled || false %>

<div class="form-group">
  <div class="col-md-5">
    <% unless disabled %>
      <%= f.select :nation_id, Nation.shipping_destinations.map{|n| [n.name, n.id]}, {}, class: 'form-control' %>
    <% else %>
      <%= f.text_field :nation_id, value: Nation.find(f.object.nation_id).name, disabled: disabled, class: 'form-control' %>
    <% end %>
  </div>
  <div class="col-md-5">
    <%= f.number_field :shipping_rate, step: 0.01, value: f.object.shipping_rate_z, disabled: disabled, class: 'form-control' %>
  </div>
  <%= link_to_remove_field(t('reward_edit.remove_nation'), f, {}) unless disabled %>
  <%= f.hidden_field :id %>
</div>

app/views/projects/_show_pledge_list.html.erb
<section>
  <div class="container modal-container">
    <h4 class="my1 text-right"><%= t('profile_pledge_modal.count', pledge_count: @pledges.size) %></h4>
    <table class="table">
      <thead>
        <tr>
          <th><%= t('pledge_model.reward') %></th>
          <th><%= t('pledge_model.user') %></th>
          <th><%= t('pledge_model.pledged_date') %></th>
          <th><%= t('pledge_model.amount') %></th>
          <th><%= t('pledge_model.shipping_rate') %></th>
          <th><%= t('pledge_model.total') %></th>
        </tr>
      </thead>

      <tbody>
        <% @pledges.each do |pledge| %>
          <tr>
            <td><%= pledge.reward.title(locale) %></td>
            <td><%= pledge.user.name %></td>
            <td><%= l pledge.pledged_at, format: :long %></td>
            <td><%= pledge.pledge_payment.amount_f %></td>
            <td><%= pledge.pledge_payment.shipping_rate_f %></td>
            <td><%= pledge.pledge_payment.total_amount_f %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/projects/complete.html.erb
<h1>Complete Payments</h1>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Category</th>
      <th>Goal amount</th>
      <th>Duration days</th>
      <th>Begin Date (applied)</th>
      <th>Image</th>
      <th>Languages</th>
      <th>Rewards</th>
      <th>Status</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.code %></td>
        <td><%= project.title(locale)  %></td>
        <td><%= project.category.name(locale) %></td>
        <td><%= project.goal_amount_f %></td>
        <td><%= project.duration_days %></td>
        <td><%= I18n.l project.applied_begin_date, format: :date %></td>
        <td><%= image_tag project.image_thumb(locale) %></td>
        <td><%= project.languages.join(',') %></td>
        <td><%= project.rewards.size %></td>
        <td><%= project.status_div.t %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Preview', preview_project_path(project) %></td>
        <td><%= link_to 'Pledges', pledges_path(project_code: project.code) %></td>
        <td><%= link_to 'Pay', pay_project_path(project) %></td>
        <td><%= link_to 'Pay Back', pay_back_project_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Project', new_project_path, data: {'no-turbolink': :true} %>-->
<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<% p = @project %>
<section class="project-hero">
  <div class="project-hero-title py4 px2">
    <div class="center">
      <h2 class="mb1"><%= p.title(locale) %></h2>
      <h5>by <%= link_to p.user.name, p.user %></h5>
    </div>
  </div>
  <div class="project-hero-content container px2">
    <div class="row">
      <div class="col-md-8">
        <div class="project-hero-image mb4">
          <%= image_tag p.image(locale) %>
        </div>
        <div class="project-hero-description">
          <div class="h5 mb3">
            <%= link_to discover_category_path(p.category), class: 'mr2' do %>
              <i class="glyphicon glyphicon-tag"></i>
              <%= p.category.name(locale) %>
            <% end %>
            <i class="glyphicon glyphicon-globe"></i>
            <% p.project_locales.each do |l|%>
              <kbd><%= l.language.code %></kbd>
            <% end %>
          </div>
          <p class="h3 mb3"><%= p.blurb(locale) %></p>
          <div class="mb3">
            <div class="social clearfix">
              <!-- Facebook -->
              <div class="button facebook">
                <div class="fb-share-button"
                  data-href="<%= request.url %>"
                  data-layout="button_count"
                  data-width="120"
                  data-show-faces="false"
                  data-mobile-iframe="true">
                </div>
              </div>
              <!-- Twitter -->
              <div class="button twitter">
                <a href="https://twitter.com/share" class="twitter-share-button"
                  data-lang="en"
                  data-url="<%= request.url %>"
                  data-text="<%= p.title(locale) %>"
                  data-hashtags="vvf,crowdfunding"
                >Tweet</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="project-hero-stats">
          <% sum = p.summary %>
          <div class="row">
            <div class="col col-md-12 mb3">
              <div><h1 class="bold"><%= sum.funded_count %></h1></div>
              <span>backers</span>
            </div>
            <div class="col col-md-12 mb3">
              <div><h1 class="bold">$<%= sum.funded_amount_f %></h1></div>
              <span>pledged of $<%= p.goal_amount_f %> goal</span>
            </div>
            <div class="col col-md-12 mb3">
              <div><h1 class="bold"><%= p.days_to_go %></h1></div>
              <span>days to go</span>
            </div>
          </div>
          <div class="project-hero-back pt4">
            <a href="#rewards-list" class="btn btn-info btn-ghost btn-block btn-lg"><%= t('prj_show_hero.back_prj') %></a>
          </div>
          <div class="py4">
            <div class="row">
              <div class="col col-md-12">
                <h6 class="mb2"><%= t('prj_show_hero.end_at', end_at: l(p.end_at, format: :date)) %></h6>
              </div>
              <div class="col col-md-8">
                <h5 class="mb1"><%= p.user.name %></h5>
                <p>
                  <%= link_to t('prj_show_hero.see_bio'), p.user %>
                </p>
              </div>
              <div class="col col-md-4">
              </div>
            </div>
          </div>
        </div>
        <div class="project-hero-bio">
        </div>
      </div>
    </div>
  </div>
</section>

<section class="project-content">
  <div class="bg-white">
    <div class="container px2">
      <div class="row">
        <div class="col col-md-8">
          <div class="mb4">
            <h3><%= t('prj_show_detail.about_prj') %></h3>
          </div>
          <div class="project-content-body">
            <%= p.body(locale).html_safe %>
          </div>
          <div class="mb4">
            <a href="#rewards-list" class= "btn btn-info btn-block"><%= t('prj_show_detail.back_prj') %></a>
          </div>
        </div>
        <div class="col col-md-4">
          <div class="mb4">
            <h3 id="rewards-list"><%= t('prj_show_reward.rewards') %></h3>
          </div>
          <ul class="list-no-style pl0">
            <% p.rewards.each do |r| %>
              <li class="reward-tile-wrap">
                <div class="reward-tile">
                  <h3 class="mb1"><%= t('prj_show_reward.reward_of', price: "$#{r.price_f}") %></h3>
                  <span class="block mb1"><%= t('prj_show_reward.left_of', left_count: r.left_count, count: r.count) %></span>
                  <div class="reward-image mb1">
                    <%= image_tag r.image(locale) %>
                  </div>
                  <div class="reward-description mb1">
                    <%= simple_format h r.description(locale) %>
                  </div>
                  <div class="reward-footer mb1">
                    <div class="reward-footer-item">
                      <span class="item-label">
                        <%= t('prj_show_reward.estimated_delivery') %>
                      </span>
                      <span class="item-data">
                        <%= l r.estimated_delivery, format: :y_m %>
                      </span>
                    </div>
                    <div class="reward-footer-item">
                      <span class="item-label"><%= t('prj_show_reward.ships_to') %></span>
                      <span class="item-data"><%= r.ships_to_div.t %></span>
                    </div>
                  </div>
                  <div class="pledge-button">
                    <%= link_to t('prj_show_reward.pledge_reward'), '#pledge-modal',
                      class: 'btn btn-info btn-block',
                      data: {toggle: 'modal', logged_in: logged_in?, reward_code: r.code} %>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="modal fade" id="pledge-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2 class="my2"><%= p.title(locale) %></h2>
        <h5 class="mb1">by <%= link_to p.user.name, p.user %></h5>
      </div>
      <div class="modal-body" id="pledge-info">
        <!-- pledge content -->
      </div>
    </div>
  </div>
</div>

<% if logged_in? %>
  <% if (@project.user == current_user || current_user.is_admin) %>
    <div class="floating-panel-right">
      <% if @project.user == current_user && (@project.status_div_temp? || @project.status_div_draft? || @project.status_div_remanded?) %>
        <h3 class="my1"><%= t('prj_show_action.this_is', what: t('prj_show_action.preview')) %></h3>
        <%= link_to t('prj_show_action.edit'), edit_project_path(@project), class: 'btn btn-default btn-lg my1' %>
        <%= link_to t('prj_show_action.apply'), apply_project_path(@project), class: 'btn btn-info btn-lg my1', data: { confirm: t('prj_show_action.confirm_to', action: t('prj_show_action.apply')) } %>
      <% elsif current_user.is_admin && @project.status_div_applied? %>
        <h3 class="my1"><%= t('prj_show_action.this_is', what: t('prj_show_action.preview')) %></h3>
        <%= link_to t('prj_show_action.remand'), remand_project_path(@project), class: 'btn btn-default btn-lg my1', data: { confirm: t('prj_show_action.confirm_to', action: t('prj_show_action.remand')) } %>
        <%= link_to t('prj_show_action.approve'), approve_project_path(@project), class: 'btn btn-info btn-lg my1', data: { confirm: t('prj_show_action.confirm_to', action: t('prj_show_action.approve')) } %>
      <% elsif @project.status_div_active? %>
        <h3 class="my1"><%= t('prj_show_action.this_is', what: t('prj_show_action.your_project')) %></h3>
        <%= link_to t('prj_show_action.suspend'), suspend_project_path(@project), class: 'btn btn-danger btn-lg my1', data: { confirm: t('prj_show_action.confirm_to', action: t('prj_show_action.suspend')) } %>
      <% elsif current_user.is_admin && @project.status_div_suspended? %>
        <h3 class="my1"><%= t('prj_show_action.this_is', what: t('prj_show_action.your_project')) %></h3>
        <%= link_to t('prj_show_action.drop'), drop_project_path(@project), class: 'btn btn-danger btn-lg my1', data: { confirm: t('prj_show_action.confirm_to', action: t('prj_show_action.drop')) } %>
        <%= link_to t('prj_show_action.resume'), resume_project_path(@project), class: 'btn btn-info btn-lg my1', data: { confirm: t('prj_show_action.confirm_to', action: t('prj_show_action.resume')) } %>
      <% else %>
        <h3 class="my1"><%= t('prj_show_action.this_project_is', status: @project.status_div.t) %></h3>
      <% end %>
    </div>
  <% end %>
<% end %>

<% content_for :ogp_meta_data do %>
  <meta property="fb:app_id" content="<%= ENV['FACEBOOK_KEY'] %>" />
  <meta property="og:title" content="<%= p.title(locale) %>" />
  <meta property="og:type" content="article" />
  <meta property="og:description" content="<%= p.blurb(locale) %>" />
  <meta property="og:url" content="<%= request.url %>" />
  <meta property="og:site_name" content="VinVin-Funding" />
  <meta property="og:image" content="<%= p.image(locale) %>" />
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@vinvin_funding">
  <meta name="twitter:title" content="<%= p.title(locale) %>">
  <meta name="twitter:description" content="<%= p.blurb(locale) %>">
  <meta name="twitter:image" content="<%= p.image(locale) %>">
<% end %>

<script type="text/javascript">
  $('#pledge-modal').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget);
    if (button.data('logged-in') === false) {
      document.location = '/login';
      return;
    }
    var reward_code = button.data('reward-code');
    var modal = $(this);
    return $.ajax({
      url: "/<%= locale %>/rewards/" + reward_code + "/new_pledge",
      type: "GET",
      data: {},
      dataType: "html",
      success: function(data, status, xhr) {
        return modal.find('#pledge-info').html(data);
      },
      error: function(xhr, status, error) {
        modal.modal('hide');
        return alert('Failed to load pledge info!!\n[Error] '+error);
      }
    });
  });
</script>

app/views/projects/start.html.erb
<div class="hero-image hero-image-start">
  <div class="start-project-wrap">
    <p class="project-start-message"><%= t('prj_start_hero.message_line_1') %></p>
    <%= link_to t('prj_start_hero.start'), new_project_path, class: 'btn btn-white btn-ghost btn-xlg mt3' %>
  </div>
</div>

<div class="container">
  <%= image_tag("about_vvf_1_#{locale}.png", width: '100%', class: 'my4') %>
</div>