config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  scope '(:locale)', locale: /en|vi|ja/ do
    root 'discover#top'
    resources :users  do
      member do
        get :activate
      end
    end
    get 'profile/:id' => 'users#profile', as: :profile
    resources :languages
    resources :categories
    resources :nations
    resources :divisions
    resources :payment_vendors
    resources :app_settings, :except => [:new, :create, :destroy]
    resources :faqs
    resources :projects do
      member do
        get 'preview' => 'projects#preview'
        get 'edit_rewards' => 'projects#edit_rewards'
        get 'discard' => 'projects#discard'
        get 'apply' => 'projects#apply'
        get 'remand' => 'projects#remand'
        get 'approve' => 'projects#approve'
        get 'resume' => 'projects#resume'
        get 'suspend' => 'projects#suspend'
        get 'drop' => 'projects#drop'
        get 'pay'
        get 'pay_back'
      end
      collection do
        get 'pledge_list'
        get 'start' => 'projects#start'
        get 'complete'
        get 'cancel'
      end
    end
    get 'project/:project_code' => 'projects#show_by_code', as: :project_by_code
    get 'rewards/:reward_code/new_pledge' => 'pledges#new', as: :new_pledge
    post 'shipping_rate' => 'pledges#shipping_rate'
    resources :pledges, :except => :new do
      member do
        get 'pay'
        get 'pay_back'
        get 'complete'
        get 'cancel'
      end
    end

    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout
    post 'user_sessions' => 'user_sessions#create', :as => :user_sessions

    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
    get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

    get 'discover/top'
    get 'discover/search'
    get 'discover/category/:id' => 'discover#category', as: :discover_category

    get 'pages/faq'
    get 'pages/news'
    get 'pages/news_body/:id' => 'pages#news_body'

    resources :password_resets
    resources :news
    resources :inquiries
    post 'inquiries/create_from_modal'
    get 'dashboard' => 'dashboard#index'
    get 'dashboard/analytics/:id' => 'dashboard#analytics', as: :dashboard_analytics
    get 'dashboard/notifications/:id' => 'dashboard#notifications', as: :dashboard_notifications
    get 'mypage/profile'
    get 'mypage/notifications'
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  sort_order :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  include SortableBase

  has_many :category_locales, dependent: :destroy
  accepts_nested_attributes_for :category_locales, allow_destroy: true

  def name(locale)
    category_locales.localed(locale).name
  end

  def get_or_new_locale(language_id)
    cl = category_locales.find { |r| r.language_id == language_id }
    cl = category_locales.langed(language_id) if cl.blank?
    cl = category_locales.build(language_id: language_id) if cl.blank?
    cl
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(
        :id,
        :sort_order,
        category_locales_attributes: [
          :id,
          :name,
          :language_id,
          :_destroy
        ]
      )
    end
end

app/views/categories/_category_locale_form.html.erb
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<%= f.hidden_field :language_id %>
<%= f.hidden_field :id %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-group">
    <div class="field">
      <%= f.label :sort_order %><br>
      <%= f.number_field :sort_order %>
    </div>
    <% Language.sorted.each do |l| %>
      <hr>
      <strong><%= f.label :language_id, l.name_en %></strong>
      <% cl = @category.get_or_new_locale(l.id) %>
      <%= f.fields_for :category_locales, cl do |clf| %>
        <%= render partial: "category_locale_form", locals: {f: clf, cl: cl} %>
      <% end %>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sort order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name(locale) %></td>
        <td><%= category.sort_order %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Sort order:</strong>
  <%= @category.sort_order %>
</p>

<p>
  <strong>Name:</strong>
  <%= @category.name(locale) %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>