config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  scope '(:locale)', locale: /en|vi|ja/ do
    root 'discover#top'
    resources :users  do
      member do
        get :activate
      end
    end
    get 'profile/:id' => 'users#profile', as: :profile
    resources :languages
    resources :categories
    resources :nations
    resources :divisions
    resources :payment_vendors
    resources :app_settings, :except => [:new, :create, :destroy]
    resources :faqs
    resources :projects do
      member do
        get 'preview' => 'projects#preview'
        get 'edit_rewards' => 'projects#edit_rewards'
        get 'discard' => 'projects#discard'
        get 'apply' => 'projects#apply'
        get 'remand' => 'projects#remand'
        get 'approve' => 'projects#approve'
        get 'resume' => 'projects#resume'
        get 'suspend' => 'projects#suspend'
        get 'drop' => 'projects#drop'
        get 'pay'
        get 'pay_back'
      end
      collection do
        get 'pledge_list'
        get 'start' => 'projects#start'
        get 'complete'
        get 'cancel'
      end
    end
    get 'project/:project_code' => 'projects#show_by_code', as: :project_by_code
    get 'rewards/:reward_code/new_pledge' => 'pledges#new', as: :new_pledge
    post 'shipping_rate' => 'pledges#shipping_rate'
    resources :pledges, :except => :new do
      member do
        get 'pay'
        get 'pay_back'
        get 'complete'
        get 'cancel'
      end
    end

    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout
    post 'user_sessions' => 'user_sessions#create', :as => :user_sessions

    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
    get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

    get 'discover/top'
    get 'discover/search'
    get 'discover/category/:id' => 'discover#category', as: :discover_category

    get 'pages/faq'
    get 'pages/news'
    get 'pages/news_body/:id' => 'pages#news_body'

    resources :password_resets
    resources :news
    resources :inquiries
    post 'inquiries/create_from_modal'
    get 'dashboard' => 'dashboard#index'
    get 'dashboard/analytics/:id' => 'dashboard#analytics', as: :dashboard_analytics
    get 'dashboard/notifications/:id' => 'dashboard#notifications', as: :dashboard_notifications
    get 'mypage/profile'
    get 'mypage/notifications'
  end

end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController
  def top
  end

  def search
    @term = params[:term].blank? ? nil : params[:term]
    if @term
      @projects = Project.search_by_term(@term)
    else
      @projects = Project.active.limit(20)
    end
  end

  def category
    @category = Category.find(params[:id])
    @projects = Project.search_by_category(@category)

    render :search
  end
end

app/views/discover/search.html.erb
<section class="pt2">
  <div class="container px2">
    <h3 class="mt1 mb3">
      <%= @projects.size %>&nbsp;<%= @category.name(locale) if @category.present? %>&nbsp;<%= 'project'.pluralize(@projects.size) %>&nbsp;<%= "of \"#{@term}\"".html_safe if @term.present? %>
    </h3>
    <% @projects.each_with_index do |p, i| %>
      <%= '<div class="row">'.html_safe if i % 4 == 0 %>
      <div class="col col-md-3 mb4">
        <div class="project-tile project-tile-tall-big">
          <div class="project-image">
            <%= link_to image_tag(p.image(locale)), project_by_code_path(p.code) %>
          </div>
          <div class="project-tile-content">
            <h5><%= link_to p.title(locale), project_by_code_path(p.code) %></h5>
            <p>by <%= link_to p.user.name, p.user %></p>
            <p class="grey-dark"><%= p.blurb(locale) %></p>
          </div>
          <div class="project-tile-footer">
            <% sum = p.summary %>
            <div class="project-tile-category-lang">
              <%= link_to discover_category_path(p.category), class: 'mr2' do %>
                <i class="glyphicon glyphicon-tag"></i>
                <%= p.category.name(locale) %>
              <% end %>
              <i class="glyphicon glyphicon-globe"></i>
              <% p.project_locales.each do |l|%>
                <kbd><%= l.language.code %></kbd>
              <% end %>
            </div>
            <div class="project-tile-status-wrap">
              <div class="project-progress-bar">
                <div class="progress">
                  <div class="progress-bar progress-bar-info" style="width:<%= sum.achieved %>%">
                  </div>
                </div>
              </div>
              <div class="project-status">
                <ul class="project-status list-inline">
                  <li class="mr1">
                    <strong class="block h5"><%= sum.achieved %>%</strong>
                    <span class="grey-dark">funded</span>
                  </li>
                  <li class="mr1">
                    <strong class="block h5">$<%= sum.funded_amount_f %></strong>
                    <span class="grey-dark">pledged</span>
                  </li>
                  <li class="mr1">
                    <strong class="block h5"><%= p.days_to_go  %></strong>
                    <span class="grey-dark">days to go</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= '</div>'.html_safe if i % 4 == 3 %>
    <% end %>
  </div>
</section>

app/views/discover/top.html.erb
<div>
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="10000">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <div class="hero-image hero-image-01">
          <div class="carousel-content-top">
            <%= image_tag 'vvf_color_mark.png', size: '140x160' %>
          </div>
          <div>
            <p class="hero-title">Vin-Vin Funding</p>
          </div>
          <div>
            <p class="hero-subtitle">New Vietnam now begins...</p>
          </div>
        </div>
        <div class="carousel-caption">
        </div>
      </div>
      <div class="item">
        <div class="hero-image hero-image-02">
          <div>
            <p class="hero-subtitle">Throw your net,</p>
            <p class="hero-sentence">GET YOUR FISHES.</p>
          </div>
          <div>
            <%= link_to 'Start a project', start_projects_path, class: 'btn btn-lg btn-white btn-ghost' %>
          </div>
        </div>
        <div class="carousel-caption">
        </div>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <%= image_tag 'vvf_line.png', class: 'hero-bottom-line' %>
</div>

<div class="favorites-area border-bottom">
  <div class="container favorites-content">
    <div class="row">
      <div class="col col-md-10">
        <div class="row">
          <h3 class="sr-only"><%= t('top_favorite.favorites') %></h3>
          <div class="tab-content">
            <% Project.favorites.each_with_index do |(c, p), i| %>
            <div id="cat-<%= c.to_s %>" class="tab-pane fade <%= 'in active' if i == 0 %>">
              <div class="projects-slider">
                <div class="row">
                  <div class="col col-md-12">
                    <div class="title">
                      <div class="row">
                        <div class="col">
                          <h3>
                            <%= link_to "#{t('top_favorite.favorites')}: #{Category.find(c).name(locale)}", discover_category_path(c) %>
                          </h3>
                        </div>
                        <div class="col col-right">
                          <%= link_to t('top_favorite.see_all_this_category'), discover_category_path(c), class: 'see-all-category' %>
                        </div>
                      </div>
                    </div>
                    <div class="project-card-wrap">
                      <div class="project-card">
                        <% if p.present? %>
                        <div class="project-image">
                          <%= link_to image_tag(p.image(locale)), project_by_code_path(p.code) %>
                        </div>
                        <div class="project-card-description">
                          <h4><%= link_to p.title(locale), project_by_code_path(p.code) %></h4>
                          <p><%= link_to p.user.name, p.user %></p>
                          <p class="grey-dark"><%= p.blurb(locale) %></p>
                          <div class="project-card-footer">
                            <div class="project-location-category">
                              <%= link_to discover_category_path(p.category), class: 'mr2' do %>
                                <i class="glyphicon glyphicon-tag"></i>
                                <%= p.category.name(locale) %>
                              <% end %>
                              <i class="glyphicon glyphicon-globe"></i>
                              <% p.project_locales.each do |l|%>
                                <kbd><%= l.language.code %></kbd>
                              <% end %>
                            </div>
                            <div class="project-status-wrap absolute-bottom">
                              <% sum = p.summary %>
                              <div class="project-progress mb1">
                                <div class="progress">
                                  <div class="progress-bar progress-bar-info" style="width:<%= sum.achieved %>%">
                                  </div>
                                </div>
                              </div>
                              <ul class="project-status list-inline">
                                <li class="mr2">
                                  <strong class="block h4">
                                    <%= sum.achieved %>%
                                  </strong>
                                  <span class="grey-dark">funded</span>
                                </li>
                                <li class="mr2">
                                  <strong class="block h4">
                                    $<%= sum.funded_amount_f %>
                                  </strong>
                                  <span class="grey-dark">pledged</span>
                                </li>
                                <li class="mr2">
                                  <strong class="block h4">
                                    <%= sum.funded_count %>
                                  </strong>
                                  <span class="grey-dark">backers</span>
                                </li>
                                <li class="mr2">
                                  <strong class="block h4">
                                    <%= p.days_to_go %>
                                  </strong>
                                  <span class="grey-dark">days to go</span>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                        <% else %>
                        <div>
                          <h4><%= t('top_favorite.no_project_msg') %></h4><br>
                        </div>
                        <div>
                          <%= link_to t('top_favorite.start'), start_projects_path,
                            class: 'btn btn-default btn-lg' %>
                        </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <div class="category-nav ml2 mt2 mr2 mb2">
          <ul class="list-no-style pl1">
            <% Category.sorted.each_with_index do |c, i| %>
              <li class="<%= 'active' if i == 0 %>">
                <%= link_to c.name(locale), "#cat-#{c.id.to_s}", data: { toggle: 'tab' } %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="recommended-area py4">
  <div class="container px2 py2">
    <div class="recommended-title pb2">
      <div class="row">
        <div class="col">
          <h3><%= t('top_recommend.recommends') %></h3>
        </div>
        <div class="col col-right">
          <%= link_to t('top_recommend.see_all'), discover_search_path, class: 'btn btn-default btn-sm' %>
        </div>
      </div>
    </div>
  </div>
  <div class="container px2 pb2">
    <div class="row">
      <% Project.active.limit(6).each do |p| %>
        <div class="col-md-4 col">
          <div class="project-tile project-tile-tall-big">
            <div class="project-image">
              <%= link_to image_tag(p.image(locale)), project_by_code_path(p.code) %>
            </div>
            <div class="project-tile-content">
              <h5><%= link_to p.title(locale), project_by_code_path(p.code) %></h5>
              <p>by <%= link_to p.user.name, p.user %></p>
              <p class="grey-dark"><%= p.blurb(locale) %></p>
            </div>
            <div class="project-tile-footer">
              <div class="project-tile-category-lang">
                <%= link_to discover_category_path(p.category), class: 'mr2' do %>
                  <i class="glyphicon glyphicon-tag"></i>
                  <%= p.category.name(locale) %>
                <% end %>
                <i class="glyphicon glyphicon-globe"></i>
                <% p.project_locales.each do |l|%>
                  <kbd><%= l.language.code %></kbd>
                <% end %>
              </div>
              <div class="project-tile-status-wrap">
                <% sum = p.summary %>
                <div class="project-progress-bar">
                  <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width:<%= sum.achieved %>%">
                    </div>
                  </div>
                </div>
                <div class="project-status">
                  <ul class="project-status list-inline">
                    <li class="mr1">
                      <strong class="block h5">
                        <%= sum.achieved %>%
                      </strong>
                      <span class="grey-dark">funded</span>
                    </li>
                    <li class="mr1">
                      <strong class="block h5">
                        $<%= sum.funded_amount_f %>
                      </strong>
                      <span class="grey-dark">pledged</span>
                    </li>
                    <li class="mr1">
                      <strong class="block h5">
                        <%= sum.funded_count %>
                      </strong>
                      <span class="grey-dark">backers</span>
                    </li>
                    <li class="mr1">
                      <strong class="block h5">
                        <%= p.days_to_go %>
                      </strong>
                      <span class="grey-dark">days to go</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="start-project-area">
  <p class="project-start-message">
    <%= t('top_start_msg.message_line_1') %><br>
    <%= t('top_start_msg.message_line_2') %>
  </p>
  <%= link_to t('top_start_msg.start'), start_projects_path, class: 'btn btn-white btn-ghost btn-lg mt2'%>
</div>

<% content_for :ogp_meta_data do %>
  <meta property="fb:app_id" content="<%= ENV['FACEBOOK_KEY'] %>" />
  <meta property="og:title" content="Vin-Vin Funding" />
  <meta property="og:type" content="article" />
  <meta property="og:description" content="Vin-Vin Funding is a platform which supports &quot;people who try something new in Vietnam&quot;" />
  <meta property="og:url" content="<%= ENV['APP_URL'] %>" />
  <meta property="og:site_name" content="VinVin-Funding" />
  <meta property="og:image" content="<%= "#{ENV['APP_URL']}#{asset_path 'vvf_top_image.png'}" %>" />
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@vinvin_funding">
  <meta name="twitter:title" content="Vin-Vin Funding">
  <meta name="twitter:description" content="Vin-Vin Funding is a platform which supports &quot;people who try something new in Vietnam&quot;">
  <meta name="twitter:image" content="<%= "#{ENV['APP_URL']}#{asset_path 'vvf_top_image.png'}" %>">
<% end %>